# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audiotransfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61udiotransfer.proto\x12\raudiotransfer\"\t\n\x07Request\"\n\n\x08Response2P\n\x08Transfer\x12\x44\n\rAudioTransfer\x12\x16.audiotransfer.Request\x1a\x17.audiotransfer.Response(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audiotransfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=47
  _globals['_RESPONSE']._serialized_start=49
  _globals['_RESPONSE']._serialized_end=59
  _globals['_TRANSFER']._serialized_start=61
  _globals['_TRANSFER']._serialized_end=141
# @@protoc_insertion_point(module_scope)
