# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audiotransfer_pb2 as audiotransfer__pb2


class TransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AudioTransfer = channel.stream_stream(
                '/audiotransfer.Transfer/AudioTransfer',
                request_serializer=audiotransfer__pb2.Request.SerializeToString,
                response_deserializer=audiotransfer__pb2.Response.FromString,
                )


class TransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AudioTransfer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AudioTransfer': grpc.stream_stream_rpc_method_handler(
                    servicer.AudioTransfer,
                    request_deserializer=audiotransfer__pb2.Request.FromString,
                    response_serializer=audiotransfer__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audiotransfer.Transfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AudioTransfer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/audiotransfer.Transfer/AudioTransfer',
            audiotransfer__pb2.Request.SerializeToString,
            audiotransfer__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
